name: publish-docs

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual/API trigger

concurrency:
  group: publish-docs
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Fern CLI tool
        uses: fern-api/setup-fern-cli@v1

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs
